# Generated by Django 2.1.5 on 2019-02-25 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grappost', '0002_auto_20190225_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='like',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postingan',
            name='like',
            field=models.ManyToManyField(related_name='postliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postingan',
            name='share',
            field=models.ManyToManyField(related_name='postshared', to=settings.AUTH_USER_MODEL),
        ),
    ]
