# Generated by Django 2.1.5 on 2019-02-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0004_auto_20190210_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
