# Generated by Django 2.1.5 on 2019-02-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0006_auto_20190214_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='emptythumbnail.png', upload_to=''),
        ),
    ]
