# Generated by Django 2.1.5 on 2019-02-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0008_auto_20190216_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
