# Generated by Django 2.1.5 on 2019-02-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0010_auto_20190218_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='like',
        ),
        migrations.RemoveField(
            model_name='course',
            name='share',
        ),
        migrations.RemoveField(
            model_name='course',
            name='view',
        ),
    ]
