# Generated by Django 2.1.5 on 2019-02-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0015_auto_20190218_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='share',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
