# Generated by Django 2.1.5 on 2019-02-20 05:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0017_auto_20190219_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
