# Generated by Django 2.1.5 on 2019-02-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0027_auto_20190224_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='mantap.png', upload_to='course/'),
        ),
    ]
