# Generated by Django 2.1.5 on 2019-02-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0028_auto_20190224_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocourse',
            name='alat_atau_bahan',
            field=models.TextField(blank=True),
        ),
    ]
