# Generated by Django 2.1.7 on 2019-03-24 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graplearn', '0031_auto_20190226_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='graplearn.Course')),
                ('like', models.ManyToManyField(blank=True, null=True, related_name='like', to=settings.AUTH_USER_MODEL)),
                ('view', models.ManyToManyField(blank=True, null=True, related_name='view', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
