# Generated by Django 2.1.7 on 2019-03-24 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0032_coursestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestatus',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursestatus',
            name='view',
            field=models.ManyToManyField(blank=True, related_name='view', to=settings.AUTH_USER_MODEL),
        ),
    ]
