# Generated by Django 2.1.7 on 2019-03-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0034_courseadvertisment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursestatus',
            old_name='view',
            new_name='student',
        ),
    ]
