# Generated by Django 2.1.7 on 2019-04-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0036_complaincourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseadvertisment',
            name='duration',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
