# Generated by Django 2.1.7 on 2019-04-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0037_courseadvertisment_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseadvertisment',
            name='start',
            field=models.DateField(),
        ),
    ]
