# Generated by Django 2.1.7 on 2019-04-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0038_auto_20190413_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseadvertisment',
            name='start',
            field=models.DateField(auto_now_add=True),
        ),
    ]
