# Generated by Django 2.1.7 on 2019-05-04 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0039_auto_20190413_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='like',
        ),
        migrations.RemoveField(
            model_name='course',
            name='share',
        ),
        migrations.RemoveField(
            model_name='course',
            name='view',
        ),
    ]
