# Generated by Django 2.1.5 on 2019-02-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0002_profile_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
