# Generated by Django 2.1.5 on 2019-02-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0003_auto_20190206_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
