# Generated by Django 2.1.5 on 2019-02-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0005_auto_20190206_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
