# Generated by Django 2.1.5 on 2019-02-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0008_auto_20190209_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='waktu_lahir',
            field=models.DateField(auto_now_add=True),
        ),
    ]
