# Generated by Django 2.1.5 on 2019-02-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0009_auto_20190209_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='koin',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
