# Generated by Django 2.1.5 on 2019-02-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0015_auto_20190218_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='like',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='share',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='view',
        ),
    ]
