# Generated by Django 2.1.5 on 2019-02-18 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('akun', '0016_auto_20190218_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dompet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uang', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_proyek', models.CharField(max_length=35)),
                ('waktu', models.DateField(auto_now_add=True)),
                ('deskripsi', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='alamat',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='deskripsi_kanal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='thumbnail',
            field=models.ImageField(blank=True, default='student.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_level',
            field=models.CharField(choices=[('1', 'Novice'), ('2', 'Beginner'), ('3', 'Competent'), ('4', 'Master'), ('5', 'Expert'), ('6', 'Legend')], default='1', max_length=1),
        ),
    ]
