# Generated by Django 2.1.5 on 2019-02-18 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0017_auto_20190218_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyek',
            old_name='nama_proyek',
            new_name='prestasi',
        ),
    ]
