# Generated by Django 2.1.5 on 2019-02-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0018_auto_20190219_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_level',
            field=models.CharField(choices=[('Novice', '1'), ('Beginner', '2'), ('Competent', '3'), ('Master', '5'), ('Expert', '5'), ('Legend', '6')], default='1', max_length=1),
        ),
    ]
