# Generated by Django 2.1.5 on 2019-02-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0019_auto_20190219_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_level',
            field=models.CharField(choices=[('1', 'Novice'), ('2', 'Beginner'), ('3', 'Competent'), ('4', 'Master'), ('5', 'Expert'), ('6', 'Legend')], default='1', max_length=1),
        ),
    ]
