# Generated by Django 2.1.5 on 2019-02-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0020_auto_20190219_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kontak',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
