# Generated by Django 2.1.5 on 2019-02-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0021_profile_kontak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyek',
            name='deskripsi',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proyek',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='proyek',
            name='prestasi',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
