# Generated by Django 2.1.5 on 2019-02-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0007_auto_20190209_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='waktu_lahir',
            field=models.DateField(),
        ),
    ]
