# Generated by Django 2.1.5 on 2019-02-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0011_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, default='empty.png', upload_to=''),
        ),
    ]
