# Generated by Django 2.1.5 on 2019-02-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0012_auto_20190214_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, default='mantap.jpg', upload_to=''),
        ),
    ]
