# Generated by Django 2.1.5 on 2019-02-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0014_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='like',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='share',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='view',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
