# Generated by Django 2.1.5 on 2019-02-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0022_auto_20190219_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kontak',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
