# Generated by Django 2.1.7 on 2019-03-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0024_mycourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_exp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
