# Generated by Django 2.1.7 on 2019-03-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0029_auto_20190327_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, default='mantap.jpg', upload_to='profilepicture/'),
        ),
    ]
