# Generated by Django 2.1.7 on 2019-03-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0030_auto_20190327_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_level',
            field=models.CharField(choices=[('1', 'Novice'), ('2', 'Beginner'), ('3', 'Competent'), ('4', 'Expert'), ('5', 'Master'), ('6', 'Legend')], default='1', max_length=1),
        ),
    ]
