# Generated by Django 2.1.7 on 2019-03-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0031_auto_20190327_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='profilebanner/'),
        ),
    ]
