# Generated by Django 2.1.7 on 2019-03-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0032_auto_20190327_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingvideo',
            name='video',
            field=models.FileField(blank=True, upload_to='openingprofilevideo/'),
        ),
    ]
