# Generated by Django 2.1.7 on 2019-03-27 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0034_auto_20190327_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimoni',
            name='receiver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
