# Generated by Django 2.1.7 on 2019-03-27 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('akun', '0035_auto_20190327_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimoni',
            name='receiver_user',
        ),
        migrations.AddField(
            model_name='testimoni',
            name='receiver_user',
            field=models.ManyToManyField(related_name='receiver_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='testimoni',
            name='sender_user',
        ),
        migrations.AddField(
            model_name='testimoni',
            name='sender_user',
            field=models.ManyToManyField(related_name='sender_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
