# Generated by Django 2.1.7 on 2019-03-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0037_auto_20190327_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourse',
            name='courses',
            field=models.ManyToManyField(blank=True, to='graplearn.Course'),
        ),
    ]
