# Generated by Django 2.1.7 on 2019-03-29 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0042_auto_20190329_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaining',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
