# Generated by Django 2.1.7 on 2019-03-29 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0036_complaincourse'),
        ('akun', '0043_complaining_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaining',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_complain_course', to='graplearn.Course'),
            preserve_default=False,
        ),
    ]
