# Generated by Django 2.1.7 on 2019-03-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0044_complaining_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
