# Generated by Django 2.1.7 on 2019-04-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0046_tukarkoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tukarkoin',
            name='selesai',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tukarkoin',
            name='waktu_dilakukan',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
