# Generated by Django 2.1.7 on 2019-04-09 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0036_complaincourse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('akun', '0047_auto_20190407_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('expired', models.BooleanField(default=False)),
                ('buyed_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graplearn.Course')),
                ('buyed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
