# Generated by Django 2.1.7 on 2019-04-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0048_expiredcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredcourse',
            name='start_date',
            field=models.DateField(),
        ),
    ]
