# Generated by Django 2.1.7 on 2019-04-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0049_auto_20190409_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredcourse',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
