# Generated by Django 2.1.7 on 2019-04-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0051_auto_20190409_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingvideo',
            name='video',
            field=models.FileField(upload_to='openingprofilevideo/'),
        ),
    ]
