# Generated by Django 2.1.7 on 2019-04-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0053_karya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karya',
            name='file',
            field=models.FileField(blank=True, upload_to='userkarya/'),
        ),
    ]
