# Generated by Django 2.1.7 on 2019-04-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0054_auto_20190411_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='line_account',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_account',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
