# Generated by Django 2.1.5 on 2019-02-10 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, upload_to='')),
                ('deskripsi', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Belum dibeli', 'Belum dibeli'), ('Terbeli', 'Terbeli')], default='reguler', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graplearn.Course'),
        ),
    ]
