# Generated by Django 2.1.5 on 2019-02-10 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0002_auto_20190210_1121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseVideo',
            new_name='VideoCourse',
        ),
    ]
