# Generated by Django 2.1.5 on 2019-02-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0003_auto_20190210_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Belum dibeli', 'Belum dibeli'), ('Terbeli', 'Terbeli'), ('Author', 'Author')], max_length=10),
        ),
    ]
