# Generated by Django 2.1.5 on 2019-02-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0009_auto_20190216_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='like',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='share',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='view',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
