# Generated by Django 2.1.5 on 2019-02-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0012_coursestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestatus',
            name='view',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
