# Generated by Django 2.1.5 on 2019-02-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0013_coursestatus_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestatus',
            name='course',
        ),
        migrations.DeleteModel(
            name='CourseStatus',
        ),
    ]
