# Generated by Django 2.1.5 on 2019-02-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0014_auto_20190218_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='like',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='share',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='view',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
