# Generated by Django 2.1.5 on 2019-02-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0016_auto_20190219_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='mantap.png', upload_to=''),
        ),
    ]
