# Generated by Django 2.1.5 on 2019-02-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0023_auto_20190224_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocourse',
            name='video',
            field=models.FileField(upload_to='coursevideos/'),
        ),
    ]
