# Generated by Django 2.1.5 on 2019-02-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0024_auto_20190224_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocourse',
            name='judul',
            field=models.CharField(default='tutorial Matematika', max_length=40),
            preserve_default=False,
        ),
    ]
