# Generated by Django 2.1.5 on 2019-02-24 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graplearn', '0025_videocourse_judul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocourse',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='graplearn.Course'),
        ),
    ]
