# Generated by Django 2.1.5 on 2019-02-25 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField()),
                ('like', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Postingan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=30)),
                ('isi', models.TextField()),
                ('file', models.FileField(blank=True, upload_to='postingan/')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('like', models.ManyToManyField(related_name='postliked', to=settings.AUTH_USER_MODEL)),
                ('share', models.ManyToManyField(related_name='postshared', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='komentar',
            name='postingan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grappost.Postingan'),
        ),
    ]
