# Generated by Django 2.1.5 on 2019-02-25 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grappost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='like',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postingan',
            name='like',
            field=models.ManyToManyField(null=True, related_name='postliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postingan',
            name='share',
            field=models.ManyToManyField(null=True, related_name='postshared', to=settings.AUTH_USER_MODEL),
        ),
    ]
