# Generated by Django 2.1.7 on 2019-03-02 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grappost', '0003_auto_20190225_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='komentar',
            name='postingan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postingan', to='grappost.Postingan'),
        ),
    ]
