# Generated by Django 2.1.7 on 2019-04-04 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grappost', '0005_auto_20190302_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
