# Generated by Django 2.1.7 on 2019-04-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grappost', '0006_komentar_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingan',
            name='kategori_post',
            field=models.CharField(choices=[('1', 'Mencari'), ('2', 'Promo')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
