# Generated by Django 2.1.7 on 2019-04-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grappost', '0007_postingan_kategori_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingan',
            name='kategori_post',
            field=models.CharField(choices=[('1', 'Mencari'), ('2', 'Promo'), ('3', 'Bertanya')], max_length=1),
        ),
    ]
