# Generated by Django 2.1.7 on 2019-04-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grappost', '0008_auto_20190405_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
