# Generated by Django 2.1.7 on 2019-04-08 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grappost', '0009_komentar_confirm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='komentar',
            old_name='confirm',
            new_name='helping',
        ),
    ]
